### ISSUE TITLE
Question: Do you call the APIs with GPT's function calling?

### ISSUE THREAD

**Issue by caizhuoyue77** [OceannTwT/Tool-Planner#4]
Hi, great paper. I wonder if you are using ChatGPT's function calling to call the APIs, I didn't find details about this in the paper.

Thanks!

**Comment by OceannTwT** [comment]
Yes, we indeed use chatgpt function calling to call APIs

`new_prediction = gpt_fact.predict_fun(functions = open_functions)`

See: [Tool-Planner](https://github.com/OceannTwT/Tool-Planner/tree/main)/[src](https://github.com/OceannTwT/Tool-Planner/tree/main/src)/[planner](https://github.com/OceannTwT/Tool-Planner/tree/main/src/planner)
/plan.py

**Comment by caizhuoyue77** [comment]
> Yes, we indeed use chatgpt function calling to call APIs
> 
> `new_prediction = gpt_fact.predict_fun(functions = open_functions)`
> 
> See: [Tool-Planner](https://github.com/OceannTwT/Tool-Planner/tree/main)/[src](https://github.com/OceannTwT/Tool-Planner/tree/main/src)/[planner](https://github.com/OceannTwT/Tool-Planner/tree/main/src/planner) /plan.py

Ok, thanks!
